@host = localhost
@port = 3000
@baseApiUrl = http://{{host}}:{{port}}/api/v1

###

// signup endpoint
POST {{baseApiUrl}}/auth/signup HTTP/1.1
Content-Type: application/json

{
    "username": "new1username16",
    "email": "awholenewEmail16@cona.co",
    "password": "louLou9209",
    "passwordConfirm": "louLou9209"
}

###

// login endpoint
POST {{baseApiUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "awholenewEmail26@cona.co",
    "password": "louLou9209"
}

###

// logout endpoint
POST {{baseApiUrl}}/auth/logout HTTP/1.1
